let H =
      https://gitlab.horizon-haskell.net/dhall/horizon-spec/-/raw/0.10.0/horizon-spec/package.dhall

let packages =
      { HTF = H.callHackage "HTF" "0.15.0.1"
      , MemoTrie = H.callHackage "MemoTrie" "0.6.11"
      , MonadPrompt = H.callHackage "MonadPrompt" "1.0.0.5"
      , Only = H.callHackage "Only" "0.1"
      , aeson = H.callHackage "aeson" "2.1.2.1"
      , algebraic-graphs = H.callHackage "algebraic-graphs" "0.7"
      , apply-refact = H.callHackage "apply-refact" "0.13.0.0"
      , attoparsec-aeson = H.callHackage "attoparsec-aeson" "2.1.0.0"
      , base-prelude = H.callHackage "base-prelude" "1.6.1.1"
      , blaze-textual = H.callHackage "blaze-textual" "0.2.3.1"
      , co-log-core = H.callHackage "co-log-core" "0.3.2.1"
      , commutative-semigroups =
          H.callHackage "commutative-semigroups" "0.1.0.1"
      , conduit-parse = H.callHackage "conduit-parse" "0.2.1.1"
      , constraints-extras = H.callHackage "constraints-extras" "0.4.0.0"
      , cpphs = H.callHackage "cpphs" "1.20.9.1"
      , cryptohash-md5 = H.callHackage "cryptohash-md5" "0.11.101.0"
      , deferred-folds = H.callHackage "deferred-folds" "0.9.18.5"
      , dependent-map = H.callHackage "dependent-map" "0.4.0.0"
      , dependent-sum = H.callHackage "dependent-sum" "0.7.2.0"
      , deriving-aeson = H.callHackage "deriving-aeson" "0.2.9"
      , direct-sqlite = H.callHackage "direct-sqlite" "2.3.28"
      , doctest = H.callHackage "doctest" "0.22.2"
      , doctest-discover = H.callHackage "doctest-discover" "0.2.0.0"
      , enummapset = H.callHackage "enummapset" "0.7.2.0"
      , filemanip = H.callHackage "filemanip" "0.3.6.3"
      , filtrable = H.callHackage "filtrable" "0.1.6.0"
      , floatshow = H.callHackage "floatshow" "0.2.4"
      , focus = H.callHackage "focus" "1.0.3.2"
      , fourmolu = H.callHackage "fourmolu" "0.14.0.0"
      , fsnotify = H.callHackage "fsnotify" "0.4.1.0"
      , fuzzy = H.callHackage "fuzzy" "0.1.0.1"
      , generic-lens = H.callHackage "generic-lens" "2.2.2.0"
      , generic-lens-core = H.callHackage "generic-lens-core" "2.2.1.0"
      , ghc-check = H.callHackage "ghc-check" "0.5.0.8"
      , ghc-exactprint = H.callHackage "ghc-exactprint" "1.6.1.3"
      , ghc-lib-parser = H.callHackage "ghc-lib-parser" "9.6.3.20231014"
      , ghc-lib-parser-ex = H.callHackage "ghc-lib-parser-ex" "9.6.0.2"
      , ghc-trace-events = H.callHackage "ghc-trace-events" "0.1.2.7"
      , ghcid = H.callHackage "ghcid" "0.8.9"
      , ghcide = H.callHackage "ghcide" "2.4.0.0"
      , ghcide-bench = H.callHackage "ghcide-bench" "2.4.0.0"
      , ghcide-test-utils = H.callHackage "ghcide-test-utils" "1.9.0.0"
      , githash = H.callHackage "githash" "0.1.7.0"
      , groups = H.callHackage "groups" "0.5.3"
      , haddock-library = H.callHackage "haddock-library" "1.11.0"
      , haskell-language-server =
          (H.callHackage "haskell-language-server" "2.4.0.0")
        with flags =
          [ H.CabalFlag.Disable "ormolu"
          , H.CabalFlag.Disable "refine-imports"
          , H.CabalFlag.Disable "rename"
          , H.CabalFlag.Disable "stylishHaskell"
          , H.CabalFlag.Disable "eval"
          , H.CabalFlag.Disable "floskell"
          ]
      , haskell-src = H.callHackage "haskell-src" "1.0.4"
      , hie-bios = H.callHackage "hie-bios" "0.12.0"
      , hie-compat = H.callHackage "hie-compat" "0.3.1.1"
      , hiedb =
          H.callGit
            "https://github.com/wz1000/HieDB"
            "62ef191df2c1ce3324c2dfc2f2a574863642435d"
            (None H.Subdir)
      , hinotify = H.callHackage "hinotify" "0.4.1"
      , hlint = H.callHackage "hlint" "3.6.1"
      , hls-alternate-number-format-plugin =
          H.callHackage "hls-alternate-number-format-plugin" "2.4.0.0"
      , hls-cabal-fmt-plugin = H.callHackage "hls-cabal-fmt-plugin" "2.4.0.0"
      , hls-cabal-plugin = H.callHackage "hls-cabal-plugin" "2.4.0.0"
      , hls-call-hierarchy-plugin =
          H.callHackage "hls-call-hierarchy-plugin" "2.4.0.0"
      , hls-change-type-signature-plugin =
          H.callHackage "hls-change-type-signature-plugin" "2.4.0.0"
      , hls-class-plugin = H.callHackage "hls-class-plugin" "2.4.0.0"
      , hls-code-range-plugin = H.callHackage "hls-code-range-plugin" "2.4.0.0"
      , hls-explicit-fixity-plugin =
          H.callHackage "hls-explicit-fixity-plugin" "2.4.0.0"
      , hls-explicit-imports-plugin =
          H.callHackage "hls-explicit-imports-plugin" "2.4.0.0"
      , hls-explicit-record-fields-plugin =
          H.callHackage "hls-explicit-record-fields-plugin" "2.4.0.0"
      , hls-fourmolu-plugin = H.callHackage "hls-fourmolu-plugin" "2.4.0.0"
      , hls-gadt-plugin = H.callHackage "hls-gadt-plugin" "2.4.0.0"
      , hls-graph = H.callHackage "hls-graph" "2.4.0.0"
      , hls-hlint-plugin = H.callHackage "hls-hlint-plugin" "2.4.0.0"
      , hls-module-name-plugin =
          H.callHackage "hls-module-name-plugin" "2.4.0.0"
      , hls-overloaded-record-dot-plugin =
          H.callHackage "hls-overloaded-record-dot-plugin" "2.4.0.0"
      , hls-plugin-api = H.callHackage "hls-plugin-api" "2.4.0.0"
      , hls-pragmas-plugin = H.callHackage "hls-pragmas-plugin" "2.4.0.0"
      , hls-qualify-imported-names-plugin =
          H.callHackage "hls-qualify-imported-names-plugin" "2.4.0.0"
      , hls-refactor-plugin = H.callHackage "hls-refactor-plugin" "2.4.0.0"
      , hls-retrie-plugin = H.callHackage "hls-retrie-plugin" "2.4.0.0"
      , hls-splice-plugin = H.callHackage "hls-splice-plugin" "2.4.0.0"
      , hls-test-utils = H.callHackage "hls-test-utils" "2.4.0.0"
      , hp2pretty = H.callHackage "hp2pretty" "0.10"
      , hspec-attoparsec = H.callHackage "hspec-attoparsec" "0.1.0.2"
      , hw-fingertree = H.callHackage "hw-fingertree" "0.1.2.1"
      , hw-hspec-hedgehog = H.callHackage "hw-hspec-hedgehog" "0.1.1.1"
      , hw-prim = H.callHackage "hw-prim" "0.6.3.2"
      , hxt = H.callHackage "hxt" "9.3.1.22"
      , hxt-charproperties = H.callHackage "hxt-charproperties" "9.5.0.0"
      , hxt-regex-xmlschema = H.callHackage "hxt-regex-xmlschema" "9.2.0.7"
      , hxt-unicode = H.callHackage "hxt-unicode" "9.0.2.4"
      , implicit-hie = H.callHackage "implicit-hie" "0.1.4.0"
      , implicit-hie-cradle = H.callHackage "implicit-hie-cradle" "0.5.0.1"
      , indexed-profunctors = H.callHackage "indexed-profunctors" "0.1.1.1"
      , keys = H.callHackage "keys" "3.12.3"
      , list-t = H.callHackage "list-t" "1.0.5.7"
      , lsp = H.callHackage "lsp" "2.2.0.0"
      , lsp-test = H.callHackage "lsp-test" "0.16.0.0"
      , lsp-types = H.callHackage "lsp-types" "2.0.2.0"
      , lucid = H.callHackage "lucid" "2.11.20230408"
      , mod = H.callHackage "mod" "0.2.0.1"
      , monad-loops = H.callHackage "monad-loops" "0.4.3"
      , monoid-subclasses = H.callHackage "monoid-subclasses" "1.2.4.1"
      , mtl-prelude = H.callHackage "mtl-prelude" "2.0.3.2"
      , network-info = H.callHackage "network-info" "0.2.1"
      , newtype-generics = H.callHackage "newtype-generics" "0.6.2"
      , opentelemetry = H.callHackage "opentelemetry" "0.8.0"
      , optparse-simple = H.callHackage "optparse-simple" "0.1.1.4"
      , ordered-containers = H.callHackage "ordered-containers" "0.2.3"
      , parsers-megaparsec = H.callHackage "parsers-megaparsec" "0.1.0.2"
      , pointed = H.callHackage "pointed" "5.0.4"
      , polyparse = H.callHackage "polyparse" "1.13"
      , primes = H.callHackage "primes" "0.2.1.0"
      , primitive-extras = H.callHackage "primitive-extras" "0.10.1.10"
      , primitive-unlifted = H.callHackage "primitive-unlifted" "2.1.0.0"
      , random-fu = H.callHackage "random-fu" "0.3.0.1"
      , rebase = H.callHackage "rebase" "1.20.1.1"
      , refact = H.callHackage "refact" "0.3.0.2"
      , regex = H.callHackage "regex" "1.1.0.2"
      , regex-applicative = H.callHackage "regex-applicative" "0.3.4"
      , regex-compat = H.callHackage "regex-compat" "0.95.2.1"
      , regex-pcre-builtin = H.callHackage "regex-pcre-builtin" "0.95.2.3.8.44"
      , rerebase = H.callHackage "rerebase" "1.20.1.1"
      , retrie = H.callHackage "retrie" "1.2.2"
      , row-types = H.callHackage "row-types" "1.0.1.2"
      , rvar = H.callHackage "rvar" "0.3.0.2"
      , sorted-list = H.callHackage "sorted-list" "0.2.2.0"
      , sqlite-simple = H.callHackage "sqlite-simple" "0.4.18.2"
      , stm-containers = H.callHackage "stm-containers" "1.2.0.3"
      , stm-hamt = H.callHackage "stm-hamt" "1.2.0.14"
      , tasty-rerun = H.callHackage "tasty-rerun" "1.1.19"
      , text-rope = H.callHackage "text-rope" "0.2"
      , time-locale-compat = H.callHackage "time-locale-compat" "0.1.1.5"
      , uuid = H.callHackage "uuid" "1.3.15"
      , vector-instances = H.callHackage "vector-instances" "3.4.2"
      , xmlgen = H.callHackage "xmlgen" "0.6.2.2"
      }

in  H.HorizonExport.MakeOverlay
      { overlayFile = "overlay.nix"
      , packagesDir = "pkgs/"
      , overlay = { compiler = "ghc-9.4.5", packages = toMap packages }
      }
