let H =
      https://gitlab.horizon-haskell.net/dhall/horizon-spec/-/raw/0.10.0/horizon-spec/package.dhall

let packages =
      { Boolean = H.callHackage "Boolean" "0.2.4"
      , Chart = H.callHackage "Chart" "1.9.5"
      , Chart-cairo = H.callHackage "Chart-cairo" "1.9.4.1"
      , HList = H.callHackage "HList" "0.5.3.0"
      , HTF = H.callHackage "HTF" "0.15.0.1"
      , HaTeX = H.callHackage "HaTeX" "3.22.4.1"
      , JuicyPixels = H.callHackage "JuicyPixels" "3.3.8"
      , MemoTrie = H.callHackage "MemoTrie" "0.6.11"
      , MonadPrompt = H.callHackage "MonadPrompt" "1.0.0.5"
      , NumInstances = H.callHackage "NumInstances" "1.4"
      , Only = H.callHackage "Only" "0.1"
      , Rlang-QQ = H.callHackage "Rlang-QQ" "0.3.1.0"
      , active = H.callHackage "active" "0.2.1"
      , aeson = H.callHackage "aeson" "2.2.1.0"
      , algebraic-graphs = H.callHackage "algebraic-graphs" "0.7"
      , apply-refact = H.callHackage "apply-refact" "0.14.0.0"
      , attoparsec-aeson = H.callHackage "attoparsec-aeson" "2.2.0.1"
      , base-prelude = H.callHackage "base-prelude" "1.6.1.1"
      , bibtex = H.callHackage "bibtex" "0.1.0.7"
      , binary-orphans = H.callHackage "binary-orphans" "1.0.4.1"
      , blaze-textual = H.callHackage "blaze-textual" "0.2.3.1"
      , bytes = H.callHackage "bytes" "0.17.3"
      , cairo = H.callHackage "cairo" "0.13.10.0"
      , circle-packing = H.callHackage "circle-packing" "0.1.0.6"
      , co-log-core = H.callHackage "co-log-core" "0.3.2.1"
      , commutative-semigroups =
          H.callHackage "commutative-semigroups" "0.1.0.2"
      , conduit-parse = H.callHackage "conduit-parse" "0.2.1.1"
      , constraints-extras = H.callHackage "constraints-extras" "0.4.0.0"
      , cpphs = H.callHackage "cpphs" "1.20.9.1"
      , cryptohash-md5 = H.callHackage "cryptohash-md5" "0.11.101.0"
      , cubicbezier = H.callHackage "cubicbezier" "0.6.0.7"
      , data-accessor = H.callHackage "data-accessor" "0.2.3.1"
      , data-accessor-transformers =
          H.callHackage "data-accessor-transformers" "0.2.1.8"
      , data-binary-ieee754 = H.callHackage "data-binary-ieee754" "0.4.4"
      , deferred-folds = H.callHackage "deferred-folds" "0.9.18.6"
      , dependent-map = H.callHackage "dependent-map" "0.4.0.0"
      , dependent-sum = H.callHackage "dependent-sum" "0.7.2.0"
      , deriving-aeson = H.callHackage "deriving-aeson" "0.2.9"
      , diagrams = H.callHackage "diagrams" "1.4.1"
      , diagrams-cairo = H.callHackage "diagrams-cairo" "1.4.2.1"
      , diagrams-contrib = H.callHackage "diagrams-contrib" "1.4.5.1"
      , diagrams-core = H.callHackage "diagrams-core" "1.5.1.1"
      , diagrams-lib = H.callHackage "diagrams-lib" "1.4.6"
      , diagrams-solve = H.callHackage "diagrams-solve" "0.1.3"
      , diagrams-svg = H.callHackage "diagrams-svg" "1.4.3.1"
      , dictionary-sharing = H.callHackage "dictionary-sharing" "0.1.0.0"
      , direct-sqlite = H.callHackage "direct-sqlite" "2.3.28"
      , doctest = H.callHackage "doctest" "0.22.2"
      , doctest-discover = H.callHackage "doctest-discover" "0.2.0.0"
      , dual-tree = H.callHackage "dual-tree" "0.2.3.1"
      , enclosed-exceptions = H.callHackage "enclosed-exceptions" "1.0.3"
      , enummapset = H.callHackage "enummapset" "0.7.2.0"
      , fast-math = H.callHackage "fast-math" "1.0.2"
      , filemanip = H.callHackage "filemanip" "0.3.6.3"
      , filtrable = H.callHackage "filtrable" "0.1.6.0"
      , floatshow = H.callHackage "floatshow" "0.2.4"
      , focus = H.callHackage "focus" "1.0.3.2"
      , force-layout = H.callHackage "force-layout" "0.4.0.6"
      , fourmolu = H.callHackage "fourmolu" "0.14.1.0"
      , fsnotify = H.callHackage "fsnotify" "0.4.1.0"
      , fuzzy = H.callHackage "fuzzy" "0.1.1.0"
      , generic-lens = H.callHackage "generic-lens" "2.2.2.0"
      , generic-lens-core = H.callHackage "generic-lens-core" "2.2.1.0"
      , ghc-check = H.callHackage "ghc-check" "0.5.0.8"
      , ghc-exactprint = H.callHackage "ghc-exactprint" "1.8.0.0"
      , ghc-lib-parser = H.callHackage "ghc-lib-parser" "9.8.1.20231121"
      , ghc-lib-parser-ex = H.callHackage "ghc-lib-parser-ex" "9.8.0.0"
      , ghc-parser = H.callHackage "ghc-parser" "0.2.6.0"
      , ghc-syntax-highlighter =
          H.callHackage "ghc-syntax-highlighter" "0.0.11.0"
      , ghc-trace-events = H.callHackage "ghc-trace-events" "0.1.2.7"
      , ghcid = H.callHackage "ghcid" "0.8.9"
      , ghcide = H.callHackage "ghcide" "2.6.0.0"
      , ghcide-bench = H.callHackage "ghcide-bench" "2.6.0.0"
      , ghcide-test-utils = H.callHackage "ghcide-test-utils" "1.9.0.0"
      , githash = H.callHackage "githash" "0.1.7.0"
      , glib = H.callHackage "glib" "0.13.10.0"
      , gnuplot = H.callHackage "gnuplot" "0.5.7"
      , groups = H.callHackage "groups" "0.5.3"
      , gtk2hs-buildtools = H.callHackage "gtk2hs-buildtools" "0.13.10.0"
      , haddock-library = H.callHackage "haddock-library" "1.11.0"
      , hashtables = H.callHackage "hashtables" "1.3.1"
      , haskell-language-server =
          (H.callHackage "haskell-language-server" "2.6.0.0")
        with flags =
          [ H.CabalFlag.Disable "ormolu"
          , H.CabalFlag.Disable "refine-imports"
          , H.CabalFlag.Disable "hlint"
          , H.CabalFlag.Disable "rename"
          , H.CabalFlag.Disable "stylishHaskell"
          , H.CabalFlag.Disable "eval"
          , H.CabalFlag.Disable "stan"
          , H.CabalFlag.Disable "floskell"
          ]
      , haskell-src = H.callHackage "haskell-src" "1.0.4"
      , here = H.callHackage "here" "1.2.14"
      , hie-bios = H.callHackage "hie-bios" "0.13.1"
      , hie-compat = H.callHackage "hie-compat" "0.3.1.2"
      , hiedb =
          H.callGit
            "https://github.com/wz1000/HieDB"
            "62ef191df2c1ce3324c2dfc2f2a574863642435d"
            (None H.Subdir)
      , hinotify = H.callHackage "hinotify" "0.4.1"
      , hlint =
          H.callGit
            "https://github.com/ndmitchell/hlint"
            "449f466bda01e782a1f1b6133f150160701ca371"
            (None H.Subdir)
      , hls-alternate-number-format-plugin =
          H.callHackage "hls-alternate-number-format-plugin" "2.6.0.0"
      , hls-cabal-fmt-plugin = H.callHackage "hls-cabal-fmt-plugin" "2.6.0.0"
      , hls-cabal-plugin = H.callHackage "hls-cabal-plugin" "2.6.0.0"
      , hls-call-hierarchy-plugin =
          H.callHackage "hls-call-hierarchy-plugin" "2.6.0.0"
      , hls-change-type-signature-plugin =
          H.callHackage "hls-change-type-signature-plugin" "2.6.0.0"
      , hls-class-plugin = H.callHackage "hls-class-plugin" "2.6.0.0"
      , hls-code-range-plugin = H.callHackage "hls-code-range-plugin" "2.6.0.0"
      , hls-explicit-fixity-plugin =
          H.callHackage "hls-explicit-fixity-plugin" "2.6.0.0"
      , hls-explicit-imports-plugin =
          H.callHackage "hls-explicit-imports-plugin" "2.6.0.0"
      , hls-explicit-record-fields-plugin =
          H.callHackage "hls-explicit-record-fields-plugin" "2.6.0.0"
      , hls-fourmolu-plugin = H.callHackage "hls-fourmolu-plugin" "2.6.0.0"
      , hls-gadt-plugin = H.callHackage "hls-gadt-plugin" "2.6.0.0"
      , hls-graph = H.callHackage "hls-graph" "2.6.0.0"
      , hls-hlint-plugin = H.callHackage "hls-hlint-plugin" "2.6.0.0"
      , hls-module-name-plugin =
          H.callHackage "hls-module-name-plugin" "2.6.0.0"
      , hls-overloaded-record-dot-plugin =
          H.callHackage "hls-overloaded-record-dot-plugin" "2.6.0.0"
      , hls-plugin-api = H.callHackage "hls-plugin-api" "2.6.0.0"
      , hls-pragmas-plugin = H.callHackage "hls-pragmas-plugin" "2.6.0.0"
      , hls-qualify-imported-names-plugin =
          H.callHackage "hls-qualify-imported-names-plugin" "2.6.0.0"
      , hls-refactor-plugin = H.callHackage "hls-refactor-plugin" "2.6.0.0"
      , hls-retrie-plugin = H.callHackage "hls-retrie-plugin" "2.6.0.0"
      , hls-semantic-tokens-plugin =
          H.callHackage "hls-semantic-tokens-plugin" "2.6.0.0"
      , hls-splice-plugin = H.callHackage "hls-splice-plugin" "2.6.0.0"
      , hls-test-utils = H.callHackage "hls-test-utils" "2.6.0.0"
      , hmatrix = H.callHackage "hmatrix" "0.20.2"
      , hp2pretty = H.callHackage "hp2pretty" "0.10"
      , hspec-attoparsec = H.callHackage "hspec-attoparsec" "0.1.0.2"
      , hspec-contrib = H.callHackage "hspec-contrib" "0.5.2"
      , hw-fingertree = H.callHackage "hw-fingertree" "0.1.2.1"
      , hw-hspec-hedgehog = H.callHackage "hw-hspec-hedgehog" "0.1.1.1"
      , hw-prim = H.callHackage "hw-prim" "0.6.3.2"
      , hxt = H.callHackage "hxt" "9.3.1.22"
      , hxt-charproperties = H.callHackage "hxt-charproperties" "9.5.0.0"
      , hxt-regex-xmlschema = H.callHackage "hxt-regex-xmlschema" "9.2.0.7"
      , hxt-unicode = H.callHackage "hxt-unicode" "9.0.2.4"
      , ihaskell = H.callHackage "ihaskell" "0.11.0.0"
      , ihaskell-aeson = H.callHackage "ihaskell-aeson" "0.3.0.1"
      , ihaskell-blaze = H.callHackage "ihaskell-blaze" "0.3.0.1"
      , ihaskell-charts = H.callHackage "ihaskell-charts" "0.3.0.1"
      , ihaskell-diagrams = H.callHackage "ihaskell-diagrams" "0.4.0.0"
      , ihaskell-gnuplot = H.callHackage "ihaskell-gnuplot" "0.1.0.1"
      , ihaskell-graphviz = H.callHackage "ihaskell-graphviz" "0.1.0.0"
      , ihaskell-hatex = H.callHackage "ihaskell-hatex" "0.2.1.1"
      , ihaskell-juicypixels = H.callHackage "ihaskell-juicypixels" "1.1.0.1"
      , ihaskell-magic = H.callHackage "ihaskell-magic" "0.3.0.1"
      , ihaskell-plot = H.callHackage "ihaskell-plot" "0.3.0.1"
      , ihaskell-widgets = H.callHackage "ihaskell-widgets" "0.4.0.0"
      , implicit-hie = H.callHackage "implicit-hie" "0.1.4.0"
      , indexed-profunctors = H.callHackage "indexed-profunctors" "0.1.1.1"
      , integration = H.callHackage "integration" "0.2.1"
      , intervals = H.callHackage "intervals" "0.9.2"
      , ipython-kernel = H.callHackage "ipython-kernel" "0.11.0.0"
      , keys = H.callHackage "keys" "3.12.3"
      , latex = H.callHackage "latex" "0.1.0.4"
      , linear = H.callHackage "linear" "1.22"
      , list-t = H.callHackage "list-t" "1.0.5.7"
      , loop = H.callHackage "loop" "0.3.0"
      , lsp = H.callHackage "lsp" "2.3.0.0"
      , lsp-test = H.callHackage "lsp-test" "0.16.0.1"
      , lsp-types = H.callHackage "lsp-types" "2.1.0.0"
      , lucid = H.callHackage "lucid" "2.11.20230408"
      , magic = H.callHackage "magic" "1.1"
      , matrices = H.callHackage "matrices" "0.5.0"
      , matrix = H.callHackage "matrix" "0.3.6.3"
      , mfsolve = H.callHackage "mfsolve" "0.3.2.2"
      , mod = H.callHackage "mod" "0.2.0.1"
      , monad-loops = H.callHackage "monad-loops" "0.4.3"
      , monoid-extras = H.callHackage "monoid-extras" "0.6.2"
      , monoid-subclasses = H.callHackage "monoid-subclasses" "1.2.4.1"
      , mtl-compat = H.callHackage "mtl-compat" "0.2.2"
      , mtl-prelude = H.callHackage "mtl-prelude" "2.0.3.2"
      , network-info = H.callHackage "network-info" "0.2.1"
      , newtype-generics = H.callHackage "newtype-generics" "0.6.2"
      , numeric-extras = H.callHackage "numeric-extras" "0.1"
      , opentelemetry = H.callHackage "opentelemetry" "0.8.0"
      , operational = H.callHackage "operational" "0.2.4.2"
      , optparse-simple = H.callHackage "optparse-simple" "0.1.1.4"
      , ordered-containers = H.callHackage "ordered-containers" "0.2.3"
      , pango = H.callHackage "pango" "0.13.10.0"
      , parsers-megaparsec = H.callHackage "parsers-megaparsec" "0.1.0.2"
      , plot =
          H.callGit
            "https://github.com/codedownio/haskell-plot"
            "dfa26022b5815bcd6a5dd6c818fcd2c4d25c6d44"
            (None H.Subdir)
      , pointed = H.callHackage "pointed" "5.0.4"
      , polyparse = H.callHackage "polyparse" "1.13"
      , primes = H.callHackage "primes" "0.2.1.0"
      , primitive-extras = H.callHackage "primitive-extras" "0.10.1.10"
      , primitive-unlifted = H.callHackage "primitive-unlifted" "2.1.0.0"
      , random-fu = H.callHackage "random-fu" "0.3.0.1"
      , rebase = H.callHackage "rebase" "1.20.2"
      , refact = H.callHackage "refact" "0.3.0.2"
      , regex = H.callHackage "regex" "1.1.0.2"
      , regex-applicative = H.callHackage "regex-applicative" "0.3.4"
      , regex-compat = H.callHackage "regex-compat" "0.95.2.1"
      , regex-pcre-builtin = H.callHackage "regex-pcre-builtin" "0.95.2.3.8.44"
      , repa = H.callHackage "repa" "3.4.1.5"
      , rerebase = H.callHackage "rerebase" "1.20.2"
      , retrie = H.callHackage "retrie" "1.2.3"
      , row-types = H.callHackage "row-types" "1.0.1.2"
      , rvar = H.callHackage "rvar" "0.3.0.2"
      , shelly = H.callHackage "shelly" "1.12.1"
      , should-not-typecheck = H.callHackage "should-not-typecheck" "2.1.0"
      , singletons = H.callHackage "singletons" "3.0.2"
      , singletons-base = H.callHackage "singletons-base" "3.3"
      , singletons-th = H.callHackage "singletons-th" "3.3"
      , size-based = H.callHackage "size-based" "0.1.3.2"
      , sorted-list = H.callHackage "sorted-list" "0.2.2.0"
      , sqlite-simple = H.callHackage "sqlite-simple" "0.4.18.2"
      , statestack = H.callHackage "statestack" "0.3.1.1"
      , stm-containers = H.callHackage "stm-containers" "1.2.0.3"
      , stm-hamt = H.callHackage "stm-hamt" "1.2.0.14"
      , storable-complex = H.callHackage "storable-complex" "0.2.3.0"
      , tasty-rerun = H.callHackage "tasty-rerun" "1.1.19"
      , testing-feat = H.callHackage "testing-feat" "1.1.1.1"
      , testing-type-modifiers =
          H.callHackage "testing-type-modifiers" "0.1.0.1"
      , text-rope = H.callHackage "text-rope" "0.2"
      , th-desugar = H.callHackage "th-desugar" "1.16"
      , time-locale-compat = H.callHackage "time-locale-compat" "0.1.1.5"
      , uuid = H.callHackage "uuid" "1.3.15"
      , vector-instances = H.callHackage "vector-instances" "3.4.2"
      , vector-space = H.callHackage "vector-space" "0.16"
      , vinyl = H.callHackage "vinyl" "0.14.3"
      , xformat = H.callHackage "xformat" "0.1.2.1"
      , xmlgen = H.callHackage "xmlgen" "0.6.2.2"
      , zeromq4-haskell = H.callHackage "zeromq4-haskell" "0.8.0"
      }

in  H.HorizonExport.MakeOverlay
      { overlayFile = "overlay.nix"
      , packagesDir = "pkgs/"
      , overlay = { compiler = "ghc-9.8.1", packages = toMap packages }
      }
